# Generated by Django 4.1.1 on 2025-10-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0005_alter_session_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
    ]
