# Generated by Django 4.1.1 on 2025-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0006_alter_session_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='isActive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
