# Generated by Django 4.1.1 on 2025-08-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionId', models.BigAutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
