# Generated by Django 4.1.1 on 2025-08-22 03:27
# Modified by Linton soon after
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_session_subject_fk'),
    ]

    operations = [
        # (a) drop the old CharField column
        migrations.RemoveField(
            model_name='session',
            name='subject',   # the old text field
        ),

        # (b) rename subject_fk -> subject
        migrations.RenameField(
            model_name='session',
            old_name='subject_fk',
            new_name='subject',
        ),

        # (c) enforce NOT NULL on the FK
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(
                to='core.subject',
                on_delete=django.db.models.deletion.DO_NOTHING,
                null=False,
            ),
        ),
    ]
