# Generated by Django 4.1.1 on 2025-08-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_finalize_subject_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
