# Generated by Django 4.1.1 on 2025-10-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subject_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
