version: '3.4'
services:
  myapp:
    container_name: devapp-cntr
    restart: always
    build:
      context: .
      dockerfile: Containerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - WATCHPACK_POLLING=true