# Simple dev spa container
FROM docker.io/node:20

# Copy TypeScript config & install react dependencies into /app
WORKDIR /app
COPY ./tsconfig.json ./package.json ./
RUN npm install

# Will make this dynamic later (bind mounts)
COPY ./public ./public
COPY ./src ./src

EXPOSE 3000
CMD ["npm", "start"]