# Generated by Django 4.1.1 on 2022-09-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
