# Generated by Django 4.1.1 on 2022-09-19 02:19

from django.db import migrations
from datetime import datetime


def create_data(apps, schema_editor):
    Session = apps.get_model('rest_api', 'Session')
    Session(startDate=datetime.now(), endDate=datetime.now(),
            subject='Init Session').save()


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
