# Importing a hardened python runtime UBI from redhat
FROM docker.io/python:3.11

# Installing all Django project dependencies in /app (cntr)
WORKDIR /app
COPY ./requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copying Django code & entrypoint script (runs collectstatic)
COPY ./src ./src
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Serving REST API on localhost:8000
EXPOSE 8000
ENTRYPOINT ["/entrypoint.sh"]
