# Simple dev container for React frontend app
FROM docker.io/node:22

# Copy TS & Vite config & install react dependencies into /app
WORKDIR /app
COPY package.json package-lock.json tsconfig.json vite.config.ts index.html ./
RUN npm install

# Hosting on localhost:3000 (using bind mounts to /src & /public in compose.yml)
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]