# Simple dev container for React frontend app
FROM docker.io/node:22

# Copy TypeScript config & install react dependencies into /app
WORKDIR /app
COPY package.json package-lock.json tsconfig.json index.html ./
RUN npm install

# Will make this dynamic later (bind mounts)
COPY ./public ./public
COPY ./src ./src

# Hosting on localhost:3000
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]