# Generated by Django 4.1.1 on 2025-09-03 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0004_alter_session_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='organize.subject'),
        ),
    ]
